apiVersion: v1
clusters:
- cluster:
    server: ${ACK_SERVER}
    certificate-authority-data: ${ACK_CA}
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: "206643149606417718"
  name: 206643149606417718-c0c6fd35f298c43e190d24bac3f7eed2a
current-context: 206643149606417718-c0c6fd35f298c43e190d24bac3f7eed2a
kind: Config
preferences: {}
users:
- name: "206643149606417718"
  user:
    client-certificate-data: ${ACK_CLIENT_CERTIFICATE}
    client-key-data: ${ACK_CLIENT_KEY}